### ISSUE TITLE
Create Automated Deployment via Pulumi

### ISSUE THREAD

**Issue by jhpyke** [moj-analytical-services/data-engineering-exports#34]
Currently this repo relies on an individual to manually deploy the infrastructure as laid out in this repo. We should instead be looking to have this deploy using an OIDC role via Github Actions.

I recommend creating a `pulumi preview` workflow _first_, to trigger on PR, and move onto the `pulumi up` workflow once you're satisfied the preview is working as intended.

**Acceptance Criteria**

- [x] A workflow is able to successfully access and deploy the stack from a github hosted runner
- [x] The role used by the runner is appropriately scoped to the needs of this repo (created as an OIDC role)
- [x] The workflow runs on PRs to preview the planned action, and again on merge into main to deploy.

**Comment by Ed-Bajo** [comment]
Closed for now and may be reopned if issue is raised again.
